### ISSUE TITLE
La versión 1.4.15 no tiene carpeta dist

### ISSUE THREAD

**Issue by MiguelArias7** [MauricioRobayo/trm-api#729]
Hola, Mauricio.
Primero, gracias por el paquete, es de gran utilidad.
Segundo, hace unos días actualicé el paquete y he tenido problemas.
Al devolverme al anterior release todo parece funcionar correctamente; noto que en la 1.4.15 no hay carpeta dist, pero no estoy seguro si el inconveniente es por eso.
Nuevamente, gracias.

**Comment by MauricioRobayo** [comment]
Hola @MiguelArias7 !

Gracias por reportar el problema, efectivamnte había cometido un error.

Podrías por favor actualizar a la última version ([v1.4.17](https://github.com/MauricioRobayo/trm-api/releases/tag/v1.4.17)) y verificar que ya todo funcione bien.

**Comment by MiguelArias7** [comment]
Todo funcionando correctamente, gracias!
